#!/bin/bash
set -e

REPO="${LLM_MEMORY_REPO:-scottf007/llm_memory}"
BRANCH="${LLM_MEMORY_BRANCH:-main}"
MEMORY_DIR="${LLM_MEMORY_HOME:-$HOME/.claude/memory}"
export LLM_MEMORY_HOME="$MEMORY_DIR"
LIB_DIR="$MEMORY_DIR/lib"
VENV_DIR="$LIB_DIR/.venv"
QUIET=false

if [ "$1" = "--update" ] || [ "$1" = "--quiet" ]; then
    QUIET=true
fi

log() {
    if [ "$QUIET" = false ]; then
        echo "$@"
    fi
}

# Warnings are NOT suppressed by --quiet and go to stderr. A step that fails
# has to say so: this installer's three worst defects all hid behind a
# discarded stderr or a swallowed exit status under `set -e`.
warn() {
    echo "  WARNING: $*" >&2
}

# --- Marker helpers for tracking llm_memory-owned files ---
# Several install targets (~/.claude/agents, ~/.claude/skills/narrative, etc.)
# may also contain files owned by other tools, so we can't blindly wipe them.
# Instead, each managed directory keeps a hidden marker file listing the
# filenames llm_memory currently owns. On every install we:
#   1. Delete files named in the old marker (things we used to ship).
#   2. Copy the new content.
#   3. Write a fresh marker listing what we now own.
# This lets us cleanly remove files that were dropped from the repo
# (e.g. a retired agent definition) without touching other tools' files.

# cleanup_from_marker: remove files listed in a marker, then delete the marker.
# Args: $1=marker_path $2=target_dir
cleanup_from_marker() {
    local marker="$1"
    local target_dir="$2"
    if [ -f "$marker" ]; then
        while IFS= read -r fname; do
            [ -z "$fname" ] && continue
            [ "${fname:0:1}" = "#" ] && continue
            rm -f "$target_dir/$fname"
        done < "$marker"
        rm -f "$marker"
    fi
}

# write_marker: write a fresh marker listing basenames from a glob.
# Args: $1=marker_path $2=source_glob (e.g. "$EXTRACTED/agents/*.md")
write_marker() {
    local marker="$1"
    local glob="$2"
    {
        echo "# Autogenerated by llm_memory install.sh — files owned by llm_memory"
        for f in $glob; do
            [ -f "$f" ] && basename "$f"
        done
    } > "$marker"
}

log "=== LLM Memory — Install ==="
log ""

# --- Step 1: Check system dependencies ---
log "[1/8] Checking system dependencies..."
MISSING=""
for cmd in jq sqlite3 python3 curl; do
    if ! command -v "$cmd" &> /dev/null; then
        MISSING="$MISSING $cmd"
    fi
done
if [ -n "$MISSING" ]; then
    echo "  Missing:$MISSING — attempting to install..."
    if command -v apt-get &> /dev/null; then
        sudo apt-get install -y $MISSING
    elif command -v brew &> /dev/null; then
        brew install $MISSING
    elif command -v pacman &> /dev/null; then
        sudo pacman -S --noconfirm $MISSING
    elif command -v dnf &> /dev/null; then
        sudo dnf install -y $MISSING
    else
        echo "  ERROR: Could not auto-install. Please install manually:$MISSING"
        exit 1
    fi
fi
log "  All dependencies found."

# --- Step 2: Download latest from GitHub ---
log "[2/8] Downloading latest version from GitHub..."
mkdir -p "$MEMORY_DIR" "$LIB_DIR"

# Token loader for private-repo support. Priority:
#   1. $GH_TOKEN env var
#   2. ~/.ssh/github_token (rides your existing Syncthing ~/.ssh sync)
#   3. $LLM_MEMORY_HOME/config/github_token (llm_memory config sync)
#   4. `gh auth token` (local gh CLI)
# No token = falls through to unauthenticated curl (public repos only).
_gh_token() {
    if [ -n "$GH_TOKEN" ]; then echo "$GH_TOKEN"; return 0; fi
    for path in "$HOME/.ssh/github_token" "$MEMORY_DIR/config/github_token"; do
        if [ -f "$path" ]; then
            tr -d '[:space:]' < "$path"
            return 0
        fi
    done
    # No token from env or file. Try the gh CLI, but treat its absence or
    # its failure (gh installed yet unauthenticated — the default state on a
    # fresh machine) as "no token", not as an error: emit nothing and return
    # 0 so the caller falls through to unauthenticated curl, as documented
    # above. A non-zero return here is fatal — `set -e` kills the installer
    # at `TOKEN=$(_gh_token)` with no message at all.
    if command -v gh >/dev/null 2>&1; then
        gh auth token 2>/dev/null || true
    fi
    return 0
}
TOKEN=$(_gh_token)
AUTH_HEADER=()
[ -n "$TOKEN" ] && AUTH_HEADER=(-H "Authorization: token $TOKEN")

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# Get the latest commit hash
REMOTE_SHA=$(curl -sf "${AUTH_HEADER[@]}" "https://api.github.com/repos/$REPO/commits/$BRANCH" | jq -r '.sha' 2>/dev/null)
if [ -z "$REMOTE_SHA" ] || [ "$REMOTE_SHA" = "null" ]; then
    # If API fails (rate limit, no network, private repo w/o token), check if we already have files
    if [ -f "$LIB_DIR/server.py" ]; then
        log "  Could not reach GitHub. Using existing installation."
    else
        echo "  ERROR: Could not reach GitHub and no existing installation found."
        echo "  Check your internet connection, and if the repo is private, ensure"
        echo "  \$GH_TOKEN is set or gh CLI is authenticated, then try again."
        exit 1
    fi
else
    # Check if we already have this version
    LOCAL_SHA=""
    if [ -f "$LIB_DIR/VERSION" ]; then
        LOCAL_SHA=$(cat "$LIB_DIR/VERSION")
    fi

    if [ "$LOCAL_SHA" = "$REMOTE_SHA" ] && [ "$1" != "--force" ]; then
        log "  Already up to date ($REMOTE_SHA)."
    else
        # Download and extract (api.github.com/tarball endpoint works for both public and private)
        curl -sL "${AUTH_HEADER[@]}" "https://api.github.com/repos/$REPO/tarball/$BRANCH" | tar xz -C "$TMPDIR"
        # The api/tarball endpoint names the top dir {user}-{repo}-{sha_short}, so
        # detect it dynamically rather than assuming the archive/refs/heads name.
        EXTRACTED=$(find "$TMPDIR" -mindepth 1 -maxdepth 1 -type d | head -1)

        if [ -z "$EXTRACTED" ] || [ ! -d "$EXTRACTED" ]; then
            echo "  ERROR: Download failed or archive structure unexpected."
            exit 1
        fi

        # Copy source files to lib directory.
        # $LIB_DIR itself is fully llm_memory-owned, but it also contains
        # .venv/, hooks/, agents/, skills/ subdirs we must preserve — so we
        # only wipe flat top-level *.py (no -r) before copying. Renamed or
        # retired scripts get cleaned up this way.
        rm -f "$LIB_DIR/"*.py
        cp "$EXTRACTED/server.py" "$LIB_DIR/"
        cp "$EXTRACTED/process_transcripts.py" "$LIB_DIR/"
        cp "$EXTRACTED/extract_conversation.py" "$LIB_DIR/"
        cp "$EXTRACTED/conversations.py" "$LIB_DIR/"
        cp "$EXTRACTED/indexer.py" "$LIB_DIR/"
        cp "$EXTRACTED/migrate_item_ids.py" "$LIB_DIR/"
        cp "$EXTRACTED/resolve_conflicts.py" "$LIB_DIR/"
        # These three used to be optional (`|| true`) from when they were new
        # to the repo. They are load-bearing now — step 8 imports merger, and
        # the /narrative pipeline imports renderer — so a silent skip leaves a
        # lib dir that cannot run the headline feature. Copy them like any
        # other required module: loudly, and fatally if missing.
        cp "$EXTRACTED/merger.py" "$LIB_DIR/"
        cp "$EXTRACTED/renderer.py" "$LIB_DIR/"
        cp "$EXTRACTED/delta_cache.py" "$LIB_DIR/"
        cp "$EXTRACTED/dashboard.py" "$LIB_DIR/"
        cp "$EXTRACTED/apply_settings.py" "$LIB_DIR/"
        cp "$EXTRACTED/requirements.txt" "$LIB_DIR/"
        cp "$EXTRACTED/settings.yaml" "$LIB_DIR/"
        cp "$EXTRACTED/claude-rules-example.md" "$LIB_DIR/"
        cp "$EXTRACTED/setup_syncthing.py" "$LIB_DIR/"
        cp "$EXTRACTED/install.sh" "$LIB_DIR/"

        # Copy hooks — $LIB_DIR/hooks is fully llm_memory-owned, wipe flat
        # *.sh so renamed/retired hook scripts don't linger.
        mkdir -p "$LIB_DIR/hooks"
        rm -f "$LIB_DIR/hooks/"*.sh
        cp "$EXTRACTED/hooks/"*.sh "$LIB_DIR/hooks/"
        chmod +x "$LIB_DIR/hooks/"*.sh

        # Copy per-client adapters. extract_conversation.py imports this
        # package, so it is not optional — a lib dir with the new
        # extract_conversation.py and no adapters/ cannot extract anything.
        # Fully llm_memory-owned: wipe the flat *.py first so a retired client
        # adapter can't linger and get imported.
        mkdir -p "$LIB_DIR/adapters"
        rm -f "$LIB_DIR/adapters/"*.py
        rm -rf "$LIB_DIR/adapters/__pycache__"
        cp "$EXTRACTED/adapters/"*.py "$LIB_DIR/adapters/"

        # Copy the lib/ package (archive_class, claim_match, certify, ...).
        # merger.py and renderer.py import it, so — exactly like adapters/
        # above — it is not optional: a lib dir with the new merger.py and no
        # lib/ package raises ImportError on the first merge.
        #
        # MIND THE DESTINATION. $LIB_DIR is itself named "lib", so the package
        # must land at $LIB_DIR/lib/, NOT $LIB_DIR/. Copying it flat would
        # scatter the package's modules among the top-level scripts and the
        # `from lib import ...` in merger.py would still fail.
        #
        # The [ -d ] guard is deliberate and is NOT the silent-skip shape this
        # installer was just swept for: lib/ genuinely does not exist in every
        # version this script installs (published main has no lib/ today), so
        # its absence is a supported state. Its presence-but-uncopyable is
        # not, which is why the cp itself has no `|| true`.
        if [ -d "$EXTRACTED/lib" ]; then
            mkdir -p "$LIB_DIR/lib"
            rm -f "$LIB_DIR/lib/"*.py
            rm -rf "$LIB_DIR/lib/__pycache__"
            cp "$EXTRACTED/lib/"*.py "$LIB_DIR/lib/"
        fi

        # Copy templates
        mkdir -p "$LIB_DIR/templates"
        cp "$EXTRACTED/templates/"* "$LIB_DIR/templates/" 2>/dev/null || true

        # Copy tests and the tools they drive (the adapter oracle lives in
        # tools/ and is imported by tests/test_adapter_oracle.py).
        mkdir -p "$LIB_DIR/tests"
        cp "$EXTRACTED/tests/"*.py "$LIB_DIR/tests/" 2>/dev/null || true
        # Fixtures are fully llm_memory-owned and now have subdirectories, so
        # the tree is wiped before copying rather than merged into. Two
        # reasons: `cp -r src/* dst/` where dst already holds a directory of
        # the same name merges under GNU cp and nests under some other cp
        # implementations, so a repeat install could leave fixtures/codex/codex
        # on one platform and not another; and a retired fixture would
        # otherwise linger forever and keep being collected by pytest.
        rm -rf "$LIB_DIR/tests/fixtures"
        mkdir -p "$LIB_DIR/tests/fixtures"
        cp -r "$EXTRACTED/tests/fixtures/." "$LIB_DIR/tests/fixtures/" 2>/dev/null || true
        mkdir -p "$LIB_DIR/tools"
        rm -f "$LIB_DIR/tools/"*.py "$LIB_DIR/tools/memory_wrap" "$LIB_DIR/tools/memory_wrap_clients.json"
        cp "$EXTRACTED/tools/"*.py "$LIB_DIR/tools/" 2>/dev/null || true
        # memory_wrap (the S3 generic client wrapper) and its per-client
        # config aren't .py files, so the glob above skips them.
        cp "$EXTRACTED/tools/memory_wrap" "$LIB_DIR/tools/memory_wrap" 2>/dev/null || true
        cp "$EXTRACTED/tools/memory_wrap_clients.json" "$LIB_DIR/tools/memory_wrap_clients.json" 2>/dev/null || true
        chmod +x "$LIB_DIR/tools/memory_wrap" 2>/dev/null || true

        # Copy skills — $LIB_DIR/skills is fully llm_memory-owned, so we
        # wipe the tree first (cheaper than a marker) then copy fresh.
        if [ -d "$EXTRACTED/skills" ]; then
            rm -rf "$LIB_DIR/skills"
            mkdir -p "$LIB_DIR/skills"
            cp -r "$EXTRACTED/skills/"* "$LIB_DIR/skills/"
        fi

        # Copy agents — clean stale agents (removed from repo) via marker,
        # then copy current set and rewrite marker.
        if [ -d "$EXTRACTED/agents" ]; then
            mkdir -p "$LIB_DIR/agents"
            cleanup_from_marker "$LIB_DIR/agents/.llm_memory_owned" "$LIB_DIR/agents"
            cp "$EXTRACTED/agents/"*.md "$LIB_DIR/agents/" 2>/dev/null || true
            write_marker "$LIB_DIR/agents/.llm_memory_owned" "$EXTRACTED/agents/*.md"
        fi

        # Store version
        echo "$REMOTE_SHA" > "$LIB_DIR/VERSION"

        if [ -n "$LOCAL_SHA" ]; then
            log "  Updated: ${LOCAL_SHA:0:8} → ${REMOTE_SHA:0:8}"
        else
            log "  Downloaded version ${REMOTE_SHA:0:8}"
        fi
    fi
fi

# --- Step 3: Python environment ---
log "[3/8] Setting up Python environment..."
if [ ! -d "$VENV_DIR" ] || [ ! -f "$VENV_DIR/bin/python3" ]; then
    rm -rf "$VENV_DIR"
    python3 -m venv "$VENV_DIR"
fi
chmod +x "$VENV_DIR/bin/python3" "$VENV_DIR/bin/pip" "$VENV_DIR/bin/pip3" "$VENV_DIR/bin/activate" 2>/dev/null || true
find "$VENV_DIR/bin" -type f -exec chmod +x {} \; 2>/dev/null || true
"$VENV_DIR/bin/python3" -m pip install -q -r "$LIB_DIR/requirements.txt"
log "  Dependencies installed."

# --- Step 4: Create directories and config ---
log "[4/8] Setting up directories and config..."
mkdir -p "$MEMORY_DIR/transcripts"
mkdir -p "$MEMORY_DIR/records"
mkdir -p "$MEMORY_DIR/config"

# Copy CLAUDE.md to synced config dir if not already there
if [ ! -f "$MEMORY_DIR/config/CLAUDE.md" ]; then
    if [ -f "$LIB_DIR/claude-rules-example.md" ]; then
        cp "$LIB_DIR/claude-rules-example.md" "$MEMORY_DIR/config/CLAUDE.md"
        log "  Copied CLAUDE.md to $MEMORY_DIR/config/"
    fi
fi
# Apply CLAUDE.md if no global one exists, or if config version is newer
if [ -f "$MEMORY_DIR/config/CLAUDE.md" ]; then
    if [ ! -f "$HOME/.claude/CLAUDE.md" ] || [ "$MEMORY_DIR/config/CLAUDE.md" -nt "$HOME/.claude/CLAUDE.md" ]; then
        cp "$MEMORY_DIR/config/CLAUDE.md" "$HOME/.claude/CLAUDE.md"
        log "  Applied CLAUDE.md to ~/.claude/CLAUDE.md"
    fi
fi

# Create Syncthing ignore file
cat > "$MEMORY_DIR/.stignore" << 'STIGNORE'
memory.db
memory.db-wal
memory.db-shm
lib/.venv
STIGNORE
log "  Directories ready."

# --- Step 5: Register MCP server ---
log "[5/8] Registering MCP server with Claude Code..."
SERVER_CONFIG="{\"type\":\"stdio\",\"command\":\"$VENV_DIR/bin/python3\",\"args\":[\"$LIB_DIR/server.py\"]}"
if command -v claude &> /dev/null; then
    # Registration failing usually just means "already configured", which is
    # why this is not fatal — but it can also mean the MCP server never gets
    # registered at all, and that is the whole product. Capture the output
    # rather than discarding it, and show it when we could not tell which.
    if MCP_ERR=$(claude mcp add-json llm_memory "$SERVER_CONFIG" --scope user 2>&1); then
        log "  MCP server registered."
    else
        log "  MCP server registration skipped (may already be configured)."
        [ -n "$MCP_ERR" ] && log "    claude CLI said: $MCP_ERR"
        log "    If llm_memory is missing from /mcp, register it manually:"
        log "      claude mcp add-json llm_memory '$SERVER_CONFIG' --scope user"
    fi
else
    log "  WARNING: 'claude' CLI not found. Add manually:"
    log "    claude mcp add-json llm_memory '$SERVER_CONFIG' --scope user"
fi

# --- Step 6: Install hooks, skills, and agents ---
log "[6/8] Installing lifecycle hooks, skills, and agents..."
LLM_MEMORY_INSTALLING=1 bash "$LIB_DIR/hooks/install_hooks.sh"

# Install skills — ~/.claude/skills may contain skills owned by other tools,
# so use a marker to clean only our own files. Marker entries are paths
# relative to ~/.claude/skills (e.g. "narrative/SKILL.md").
if [ -d "$LIB_DIR/skills" ]; then
    mkdir -p "$HOME/.claude/skills"
    cleanup_from_marker "$HOME/.claude/skills/.llm_memory_owned" "$HOME/.claude/skills"
    for skill_dir in "$LIB_DIR/skills"/*/; do
        [ -d "$skill_dir" ] || continue
        skill_name=$(basename "$skill_dir")
        mkdir -p "$HOME/.claude/skills/$skill_name"
        cp "$skill_dir"* "$HOME/.claude/skills/$skill_name/" 2>/dev/null || true
    done
    {
        echo "# Autogenerated by llm_memory install.sh — files owned by llm_memory"
        for skill_dir in "$LIB_DIR/skills"/*/; do
            [ -d "$skill_dir" ] || continue
            skill_name=$(basename "$skill_dir")
            for f in "$skill_dir"*; do
                [ -f "$f" ] && echo "$skill_name/$(basename "$f")"
            done
        done
    } > "$HOME/.claude/skills/.llm_memory_owned"
    log "  Skills installed to ~/.claude/skills/"
fi

# Install agents — ~/.claude/agents may contain agents owned by other tools,
# so we use a marker to clean only our own files before copying fresh ones.
if [ -d "$LIB_DIR/agents" ]; then
    mkdir -p "$HOME/.claude/agents"
    cleanup_from_marker "$HOME/.claude/agents/.llm_memory_owned" "$HOME/.claude/agents"
    cp "$LIB_DIR/agents/"*.md "$HOME/.claude/agents/" 2>/dev/null || true
    write_marker "$HOME/.claude/agents/.llm_memory_owned" "$LIB_DIR/agents/*.md"
    log "  Agents installed to ~/.claude/agents/"
fi

# --- Step 7: Apply shared settings ---
log "[7/8] Applying shared settings..."
if [ -f "$LIB_DIR/settings.yaml" ]; then
    if "$VENV_DIR/bin/python3" "$LIB_DIR/apply_settings.py" "$LIB_DIR/settings.yaml"; then
        log "  Applied shared settings from settings.yaml"
    else
        log "  WARNING: failed to apply shared settings from settings.yaml (see error above)"
    fi
fi

# --- Step 8: Initialize database and process transcripts ---
log "[8/8] Initializing database..."

# There is no separate DB-init step, by design. memory.db is derived, not
# authoritative: indexer.rebuild_items_index() (called at the end of this
# step) creates the file and the entire schema — the `items` table, its three
# indexes and the items_fts virtual table, all CREATE ... IF NOT EXISTS — and
# it is the only thing in the shipped tree that defines any schema at all.
# Nothing needs a table before then: server.py reads through
# indexer.search_items(), which returns [] when the DB is missing, and
# dashboard.py's get_db() returns None.
#
# `from server import init_db; init_db()` used to be called right here.
# init_db does not exist in server.py — it is an orphaned reference — and
# with stderr discarded under `set -e` it silently killed EVERY fresh install
# at this line, printing the banner above and then nothing whatsoever.

# Collect any existing transcripts from Claude's project dirs
for src in "$HOME/.claude/projects"/*/*.jsonl; do
    [ -f "$src" ] || continue
    base=$(basename "$src")
    [ -f "$MEMORY_DIR/transcripts/$base" ] || cp "$src" "$MEMORY_DIR/transcripts/$base" 2>/dev/null
done

# Ensure every transcript has an archived copy and a conversation.md sibling.
if [ "$QUIET" = false ]; then
    "$VENV_DIR/bin/python3" -c "
import sys
sys.path.insert(0, '$LIB_DIR')
from process_transcripts import find_transcripts
from conversations import iter_sessions
from collections import defaultdict

transcripts = find_transcripts()
if not transcripts:
    print('  No existing transcripts found.')
    sys.exit(0)

projects = defaultdict(int)
for fm in iter_sessions():
    projects[fm.get('project') or 'unknown'] += 1
print(f'  Found {len(transcripts)} transcripts across {len(projects)} projects:')
for name in sorted(projects):
    print(f'    {name:25s} {projects[name]:3d} sessions')
" || warn "could not summarise existing transcripts (see error above)."
fi

if "$VENV_DIR/bin/python3" "$LIB_DIR/process_transcripts.py" --quiet; then
    log "  Transcripts scanned."
else
    warn "process_transcripts.py failed (see error above); transcripts were NOT scanned."
fi

# Idempotent migration: rewrite integer-suffix item IDs to UUID suffixes.
"$VENV_DIR/bin/python3" "$LIB_DIR/migrate_item_ids.py" \
    || warn "item-ID migration failed (see error above); existing item IDs are unchanged."

# Fan out items from each {project}.json to ~/.claude/memory/items/ so they
# can be synced and indexed, then rebuild the FTS5 index that memory_search
# queries.
if "$VENV_DIR/bin/python3" -c "
import sys, json
sys.path.insert(0, '$LIB_DIR')
from tools.memory_config import memory_root
from merger import fan_out_items
import indexer
projects_dir = memory_root() / 'projects'
for p in sorted(projects_dir.glob('*.json')):
    try:
        state = json.loads(p.read_text())
    except Exception:
        continue
    fan_out_items(state, p.stem, memory_root() / 'items')
indexer.rebuild_items_index()
"; then
    log "  Items fanned out and index rebuilt."
else
    warn "item fan-out / index rebuild FAILED (see error above)."
    warn "memory.db is created by this step — memory_search will find nothing until it succeeds."
fi

# --- Convenience symlink for dashboard ---
mkdir -p "$HOME/.local/bin"
ln -sf "$LIB_DIR/dashboard.sh" "$HOME/.local/bin/llm-memory-dashboard"
log "  Dashboard available as: llm-memory-dashboard"

log ""
log "=== Install complete ==="
log ""
log "What happens next:"
log "  1. Start a new Claude Code session (the MCP server activates on startup)"
log "  2. Session hooks will auto-load your project context"
log "  3. Auto-updates are checked on each session start"
log ""
log "For multi-device sync with Syncthing:"
log "  python3 $LIB_DIR/setup_syncthing.py"
log ""
log "One-liner to install on another machine:"
log "  curl -sL https://raw.githubusercontent.com/$REPO/$BRANCH/install.sh | bash"
